'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
' VB.NET twin of Source\Krypton Ribbon Examples\Quick Access Toolbar\Properties\Resources.Designer.cs (Bastion Phase 4c).

Option Strict On
Option Explicit On

Namespace My.Resources

    ''' <summary>
    '''   A strongly-typed resource class, for looking up localized strings, etc.
    ''' </summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>
    Friend Module Resources

        Private resourceMan As Global.System.Resources.ResourceManager

        Private resourceCulture As Global.System.Globalization.CultureInfo

        ''' <summary>
        '''   Returns the cached ResourceManager instance used by this class.
        ''' </summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("QuickAccessToolbar.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property

        ''' <summary>
        '''   Overrides the current thread's CurrentUICulture property for all
        '''   resource lookups using this strongly typed resource class.
        ''' </summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set(value As Global.System.Globalization.CultureInfo)
                resourceCulture = value
            End Set
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property flag_australia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("flag_australia", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property flag_cameroon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("flag_cameroon", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property flag_canada() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("flag_canada", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property flag_czech_republic() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("flag_czech_republic", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property flag_egypt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("flag_egypt", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property flag_france() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("flag_france", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property flag_hong_kong() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("flag_hong_kong", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property flag_italy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("flag_italy", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property flag_lithuania() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("flag_lithuania", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property flag_new_zealand() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("flag_new_zealand", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property flag_peru() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("flag_peru", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property flag_wales() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("flag_wales", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
