<#
=====================================================================================
 build-docs.ps1 - Bastion Krypton Suite documentation build (spec §7.2, Phase 6)
 (c) Bastion Software Solutions Ltd 2026. Derived-work tooling (core BSD-3-Clause,
 Extended MIT). UK English.

 Produces the three API-help outputs from ONE repeatable, idempotent script:
   1. DocFX static site  -> docs-site\            (ready for GitHub Pages) + link-check
   2. CHM                -> Help\BastionKryptonSuite.chm      (Sandcastle Help File Builder)
   3. PDF developer guide-> Help\BastionKryptonSuite-Manual.pdf (pandoc + wkhtmltopdf)
 Plus an XML-doc coverage report -> docs\audit\XMLDOC-COVERAGE.md.

 USAGE (run from the repository root):
   .\build-docs.ps1 -All        # coverage + site + chm + pdf
   .\build-docs.ps1 -Site       # DocFX site + link-check only
   .\build-docs.ps1 -Chm        # CHM only
   .\build-docs.ps1 -Pdf        # PDF only
   .\build-docs.ps1 -Coverage   # XML-doc coverage report only
 (any combination of switches may be given; -All implies all four)

 PREREQUISITE: the suite's net8.0-windows assemblies + XML doc files must already be
 built (Phase 2 output). This script consumes them; it does not build the libraries.
   Core:     Standard-Toolkit\Bin\Release\net8.0-windows\*.dll + *.xml
   Extended: Extended-Toolkit\Bin\Release\Krypton.Toolkit.Suite.Extended.Ultimate\net8.0-windows\

 ----------------------------------------------------------------------------------
 CI notes (Phase 8):
   * The DocFX site + the XML-doc coverage report are fully CI-friendly on any
     windows-latest (or even linux) runner: they need only the .NET SDK, the docfx
     dotnet tool, and the prebuilt net8 assemblies+XML. GitHub Actions CAN build and
     publish docs-site\ to GitHub Pages.
   * The CHM needs WINDOWS-ONLY tooling: Sandcastle Help File Builder (SHFB) + HTML Help
     Workshop (hhc.exe) + desktop MSBuild. windows-latest runners do not have these by
     default - install SHFB/HHW in the job or run this step on a self-hosted Windows
     agent. It CANNOT be produced on Linux/macOS.
   * The PDF needs wkhtmltopdf + pandoc installed on the runner (both are available for
     windows-latest via choco/winget; wkhtmltopdf is Windows/Linux, so a Linux runner
     with pandoc+wkhtmltopdf can also produce it).
   * Generated outputs (docs-site\, Help\*.chm, Help\*.pdf, artifacts\) are NOT committed
     - they are build artefacts regenerated by CI/release.
 =====================================================================================
#>
[CmdletBinding()]
param(
    [switch]$Site,
    [switch]$Chm,
    [switch]$Pdf,
    [switch]$Coverage,
    [switch]$All
)

$ErrorActionPreference = 'Stop'
$RepoRoot = Split-Path -Parent $MyInvocation.MyCommand.Definition
Set-Location $RepoRoot

if (-not ($Site -or $Chm -or $Pdf -or $Coverage -or $All)) {
    Write-Host "No target selected. Use -All, or any of -Site -Chm -Pdf -Coverage." -ForegroundColor Yellow
    exit 2
}
if ($All) { $Site = $true; $Chm = $true; $Pdf = $true; $Coverage = $true }

# --------------------------------------------------------------------------- tools
$DocFx      = Join-Path $env:USERPROFILE '.dotnet\tools\docfx.exe'
$Pandoc     = Join-Path $env:LOCALAPPDATA 'Pandoc\pandoc.exe'
$WkHtml     = 'C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe'
$Hhc        = 'C:\Program Files (x86)\HTML Help Workshop\hhc.exe'
# No trailing backslash: it is passed via /p:SHFBROOT and a trailing '\' would escape the
# closing quote in MSBuild arg parsing. The .targets import adds the separator itself.
$ShfbRoot   = 'C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder'
$MSBuild    = 'C:\Program Files\Microsoft Visual Studio\18\Community\MSBuild\Current\Bin\MSBuild.exe'

# ------------------------------------------------------------------------- key paths
$CoreBin    = Join-Path $RepoRoot 'Standard-Toolkit\Bin\Release\net8.0-windows'
$ExtBin     = Join-Path $RepoRoot 'Extended-Toolkit\Bin\Release\Krypton.Toolkit.Suite.Extended.Ultimate\net8.0-windows'
$StageDir   = Join-Path $RepoRoot 'artifacts\docfx-asm'
$SiteDir    = Join-Path $RepoRoot 'docs-site'
$HelpDir    = Join-Path $RepoRoot 'Help'
$ShfbProj   = Join-Path $HelpDir 'BastionKryptonSuite.shfbproj'
$ChmPath    = Join-Path $HelpDir 'BastionKryptonSuite.chm'
$PdfPath    = Join-Path $HelpDir 'BastionKryptonSuite-Manual.pdf'
$CoveragePath = Join-Path $RepoRoot 'docs\audit\XMLDOC-COVERAGE.md'
$DocFxJson  = Join-Path $RepoRoot 'docfx.json'
$HelpSrc    = Join-Path $RepoRoot 'docs\help'

$CoreAsms = @('Krypton.Toolkit','Krypton.Ribbon','Krypton.Navigator','Krypton.Workspace','Krypton.Docking')

function Require-File($path, $what) {
    if (-not (Test-Path -LiteralPath $path)) {
        throw "$what not found: $path"
    }
}

function Write-Step($msg) { Write-Host "`n==== $msg ====" -ForegroundColor Cyan }

# --------------------------------------------------------------------- stage assemblies
# Copies the net8 core + Extended module assemblies (and their XML + all sibling
# dependency DLLs) into artifacts\docfx-asm so both DocFX metadata and SHFB read one
# self-contained folder with full dependency resolution. Idempotent.
function Update-Stage {
    Write-Step "Staging net8.0-windows assemblies -> artifacts\docfx-asm"
    Require-File $CoreBin 'Core net8 bin directory'
    Require-File $ExtBin  'Extended Ultimate net8 bin directory'

    if (Test-Path -LiteralPath $StageDir) { Remove-Item -LiteralPath $StageDir -Recurse -Force }
    New-Item -ItemType Directory -Path $StageDir -Force | Out-Null

    # Core five (dll + xml + pdb).
    foreach ($a in $CoreAsms) {
        foreach ($ext in 'dll','xml') {
            $src = Join-Path $CoreBin "$a.$ext"
            Require-File $src "Core $a.$ext"
            Copy-Item -LiteralPath $src -Destination $StageDir -Force
        }
    }
    # Everything in the Extended Ultimate output (module dll+xml plus third-party deps for
    # reference resolution). Excludes nothing - deps must be present to resolve.
    Get-ChildItem -LiteralPath $ExtBin -File | Where-Object { $_.Extension -in '.dll','.xml' } |
        ForEach-Object { Copy-Item -LiteralPath $_.FullName -Destination $StageDir -Force }

    $dllCount = (Get-ChildItem $StageDir -Filter *.dll).Count
    Write-Host "Staged $dllCount DLLs."
}

# --------------------------------------------------------------------- repair dead xrefs
# DocFX renders a type's namespace breadcrumb as one xref link per dotted segment
# (e.g. "Krypton.Navigator" -> <a href="Krypton.html">Krypton</a>.<a href="Krypton.Navigator.html">Navigator</a>).
# Intermediate segments that are not themselves a documented namespace (Krypton,
# System, Krypton.Toolkit.Suite, ...) have no generated page, leaving a dead link. This
# rewrites those specific dead same-folder xref anchors to plain text. Anchors whose
# target page exists are left untouched. Idempotent.
function Repair-DeadXrefs($apiDir) {
    if (-not (Test-Path -LiteralPath $apiDir)) { return 0 }
    $existing = @{}
    Get-ChildItem -LiteralPath $apiDir -Filter *.html | ForEach-Object { $existing[$_.Name] = $true }
    $rx = [regex]'<a class="xref" href="([^"/]+\.html)">([^<]*)</a>'
    $fixed = 0
    foreach ($f in Get-ChildItem -LiteralPath $apiDir -Filter *.html) {
        $html = Get-Content -LiteralPath $f.FullName -Raw
        $new = $rx.Replace($html, {
            param($m)
            if ($existing.ContainsKey($m.Groups[1].Value)) { return $m.Value }
            return $m.Groups[2].Value
        })
        if ($new -ne $html) {
            Set-Content -LiteralPath $f.FullName -Value $new -NoNewline -Encoding UTF8
            $fixed++
        }
    }
    return $fixed
}

# --------------------------------------------------------------------- link checker
# Parses every generated HTML page for local href/src targets and asserts they exist in
# the output. Returns the number of broken links (0 = pass). DocFX has no built-in checker.
function Test-SiteLinks($siteRoot) {
    Write-Step "Link-checking $siteRoot"
    $htmlFiles = Get-ChildItem -LiteralPath $siteRoot -Recurse -Filter *.html
    if ($htmlFiles.Count -eq 0) { throw "No HTML produced in $siteRoot" }

    $rootFull = (Resolve-Path $siteRoot).Path.TrimEnd('\')
    $broken = New-Object System.Collections.Generic.List[string]
    $checked = 0

    $rx = [regex]'(?:href|src)\s*=\s*"([^"]+)"'
    foreach ($f in $htmlFiles) {
        $html = Get-Content -LiteralPath $f.FullName -Raw
        foreach ($m in $rx.Matches($html)) {
            $link = $m.Groups[1].Value.Trim()
            if ([string]::IsNullOrWhiteSpace($link)) { continue }
            # Skip external / non-file schemes and pure anchors.
            if ($link -match '^(https?:|mailto:|javascript:|data:|tel:|#|//)') { continue }
            # Strip query + anchor.
            $target = ($link -split '[?#]')[0]
            if ([string]::IsNullOrWhiteSpace($target)) { continue }
            # URL-decode.
            $target = [System.Uri]::UnescapeDataString($target)
            # Resolve to a filesystem path.
            if ($target.StartsWith('/')) {
                $resolved = Join-Path $rootFull ($target.TrimStart('/').Replace('/','\'))
            } else {
                $resolved = Join-Path $f.DirectoryName ($target.Replace('/','\'))
            }
            try { $resolved = [System.IO.Path]::GetFullPath($resolved) } catch { continue }
            $checked++
            $exists = Test-Path -LiteralPath $resolved
            if (-not $exists -and (Test-Path -LiteralPath $resolved -PathType Container)) { $exists = $true }
            if (-not $exists -and $resolved.EndsWith('\')) {
                $exists = Test-Path -LiteralPath (Join-Path $resolved 'index.html')
            }
            if (-not $exists) {
                $rel = $f.FullName.Substring($rootFull.Length + 1)
                $broken.Add("$rel  ->  $link")
            }
        }
    }

    Write-Host "Checked $checked local links across $($htmlFiles.Count) pages."
    if ($broken.Count -gt 0) {
        Write-Host "BROKEN LINKS ($($broken.Count)):" -ForegroundColor Red
        $broken | Select-Object -Unique | ForEach-Object { Write-Host "  $_" -ForegroundColor Red }
    } else {
        Write-Host "No broken links." -ForegroundColor Green
    }
    return ($broken | Select-Object -Unique).Count
}

# ============================================================================ COVERAGE
function Invoke-Coverage {
    Write-Step "XML-doc coverage report"
    $tool = Join-Path $RepoRoot 'Scripts\DocCoverage'
    $exe  = Join-Path $tool 'bin\Release\net10.0\DocCoverage.exe'
    Write-Host "Building DocCoverage tool..."
    & dotnet build (Join-Path $tool 'DocCoverage.csproj') -c Release -v q --nologo
    if ($LASTEXITCODE -ne 0) { throw "DocCoverage build failed." }
    Require-File $exe 'DocCoverage.exe'

    # NB: do not use $args here - it is a PowerShell automatic variable inside a function.
    $covArgs = @($CoveragePath)
    foreach ($a in $CoreAsms) { $covArgs += (Join-Path $CoreBin "$a.dll") }
    Get-ChildItem -LiteralPath $ExtBin -Filter 'Krypton.Toolkit.Suite.Extended.*.dll' |
        Where-Object { $_.BaseName -notlike '*Ultimate' -and $_.BaseName -notlike '*Ultimate.Lite' } |
        ForEach-Object { $covArgs += $_.FullName }

    # Relax stderr-as-error (the tool may print 'warning:' lines to stderr); judge by exit code.
    $prevEap = $ErrorActionPreference
    $ErrorActionPreference = 'Continue'
    try {
        & $exe @covArgs 2>&1 | ForEach-Object { Write-Host $_ }
        $code = $LASTEXITCODE
    } finally { $ErrorActionPreference = $prevEap }
    if ($code -ne 0) { throw "DocCoverage run failed (exit $code)." }
    Require-File $CoveragePath 'coverage report'
    Write-Host "Coverage report: $CoveragePath" -ForegroundColor Green
}

# ================================================================================ SITE
function Invoke-Site {
    Write-Step "DocFX site -> docs-site"
    Require-File $DocFx 'docfx.exe'
    Update-Stage

    # Clean previous generated API metadata + site for a deterministic build.
    foreach ($d in @((Join-Path $HelpSrc 'api'), (Join-Path $HelpSrc 'api-extended'), $SiteDir)) {
        if (Test-Path -LiteralPath $d) { Remove-Item -LiteralPath $d -Recurse -Force }
    }

    Write-Host "docfx metadata..."
    & $DocFx metadata $DocFxJson
    if ($LASTEXITCODE -ne 0) { throw "docfx metadata failed." }

    Write-Host "docfx build..."
    & $DocFx build $DocFxJson
    if ($LASTEXITCODE -ne 0) { throw "docfx build failed." }
    Require-File (Join-Path $SiteDir 'index.html') 'docs-site\index.html'

    $r1 = Repair-DeadXrefs (Join-Path $SiteDir 'api')
    $r2 = Repair-DeadXrefs (Join-Path $SiteDir 'api-extended')
    Write-Host "Repaired dead namespace-segment xrefs in $($r1 + $r2) API page(s)."

    $brokenCount = Test-SiteLinks $SiteDir
    if ($brokenCount -gt 0) { throw "Link-check FAILED: $brokenCount broken link(s)." }

    $pages = (Get-ChildItem -LiteralPath $SiteDir -Recurse -Filter *.html).Count
    Write-Host "DocFX site OK: $pages HTML pages, link-check passed -> $SiteDir" -ForegroundColor Green
}

# ================================================================================= CHM
function Invoke-Chm {
    Write-Step "CHM -> Help\BastionKryptonSuite.chm"
    Require-File $MSBuild 'desktop MSBuild.exe'
    Require-File (Join-Path $ShfbRoot 'SandcastleHelpFileBuilder.targets') 'SHFB targets'
    Require-File $Hhc 'HTML Help Workshop hhc.exe'
    Update-Stage

    if (Test-Path -LiteralPath $ChmPath) { Remove-Item -LiteralPath $ChmPath -Force }

    # SHFB's BuildHelp task resolves its tools/reflection data from the SHFBROOT *environment*
    # variable, not only the MSBuild property. Set both.
    $env:SHFBROOT = $ShfbRoot + '\'
    & $MSBuild $ShfbProj /p:Configuration=Release "/p:SHFBROOT=$ShfbRoot" /v:minimal /nologo
    if ($LASTEXITCODE -ne 0) { throw "SHFB/MSBuild CHM build failed (see Help\Working\ or LastBuild.log)." }

    Require-File $ChmPath 'BastionKryptonSuite.chm'
    $sizeKB = [math]::Round((Get-Item $ChmPath).Length / 1KB)
    Write-Host "CHM produced: $ChmPath ($sizeKB KB)"
    if ($sizeKB -lt 300) {
        throw "CHM is implausibly small ($sizeKB KB) - TOC/topics likely missing."
    }

    # Confirm from the SHFB/HHC log that the compile completed and that a table of contents
    # (.hhc) and keyword index (.hhk) were generated with a non-trivial topic count.
    # (CleanIntermediates removes the working files, so we verify via the log.)
    # SHFB's LastBuild.log is an XML build log; completion is the final <buildStep step="Completed">
    # marker (the "help file is located at" text is console-only and not in this file).
    $log = Join-Path $HelpDir 'LastBuild.log'
    if (Test-Path -LiteralPath $log) {
        $logText = Get-Content -LiteralPath $log -Raw
        if ($logText -notmatch '<buildStep step="Completed"') {
            throw "SHFB log does not show a Completed build step - inspect $log."
        }
        $hasToc   = $logText -match 'table of contents to .*\.hhc'
        $hasIndex = $logText -match 'keyword index to .*\.hhk'
        $topics   = if ($logText -match '([\d,]+)\s+Topics') { $Matches[1] } else { '?' }
        if (-not $hasToc)   { throw "CHM log shows no table of contents (.hhc)." }
        if (-not $hasIndex) { throw "CHM log shows no keyword index (.hhk)." }
        Write-Host "SHFB completion confirmed. TOC (.hhc) + index (.hhk) present; topics: $topics." -ForegroundColor Green
    }
    Write-Host "CHM OK ($sizeKB KB)." -ForegroundColor Green
}

# ================================================================================= PDF
function Invoke-Pdf {
    Write-Step "PDF developer guide -> Help\BastionKryptonSuite-Manual.pdf"
    Require-File $Pandoc 'pandoc.exe'
    Require-File $WkHtml 'wkhtmltopdf.exe'
    New-Item -ItemType Directory -Path $HelpDir -Force | Out-Null

    # Ordered conceptual chapters (NOT the full member dump) + concise Extended module pages.
    $ordered = @(
        'index.md','getting-started.md','theming-guide.md','migration-from-upstream.md',
        'per-tfm-feature-matrix.md',
        'components\toolkit.md','components\ribbon.md','components\navigator.md',
        'components\workspace.md','components\docking.md',
        'extended\index.md'
    )
    $files = @()
    foreach ($rel in $ordered) {
        $p = Join-Path $HelpSrc $rel
        if (Test-Path -LiteralPath $p) { $files += $p }
    }
    # Append the concise per-module Extended pages (alphabetical), excluding index.
    Get-ChildItem -LiteralPath (Join-Path $HelpSrc 'extended') -Filter *.md |
        Where-Object { $_.Name -ne 'index.md' } | Sort-Object Name |
        ForEach-Object { $files += $_.FullName }

    if ($files.Count -eq 0) { throw "No markdown chapters found for the PDF." }

    if (Test-Path -LiteralPath $PdfPath) { Remove-Item -LiteralPath $PdfPath -Force }

    $pandocArgs = @()
    $pandocArgs += $files
    $pandocArgs += @(
        '--from=gfm',
        '--resource-path', $HelpSrc,
        '-o', $PdfPath,
        "--pdf-engine=$WkHtml",
        '--toc', '--toc-depth=2',
        '--standalone',
        '--metadata', 'title=Bastion Krypton Suite - Developer Guide',
        '--metadata', 'author=Bastion Software Solutions Ltd',
        '--metadata', 'date=2026',
        '-V', 'margin-top=18', '-V', 'margin-bottom=20',
        '-V', 'margin-left=16', '-V', 'margin-right=16',
        '--pdf-engine-opt=--enable-local-file-access',
        '--pdf-engine-opt=--footer-center', '--pdf-engine-opt=Page [page] of [topage]',
        '--pdf-engine-opt=--footer-font-size', '--pdf-engine-opt=8',
        '--pdf-engine-opt=--footer-spacing', '--pdf-engine-opt=4'
    )
    # wkhtmltopdf writes progress ("Loading pages (1/6)", ...) to stderr; under
    # $ErrorActionPreference='Stop' PowerShell would turn that into a terminating error even
    # on success. Relax it for the call and judge success by the exit code + output file.
    # It also drops temp files (to*.html/pdf) in the CWD, so run from a scratch dir.
    $scratch = Join-Path $RepoRoot 'artifacts'
    New-Item -ItemType Directory -Path $scratch -Force | Out-Null
    $prevEap = $ErrorActionPreference
    $ErrorActionPreference = 'Continue'
    Push-Location $scratch
    try {
        & $Pandoc @pandocArgs 2>&1 | ForEach-Object { Write-Host $_ }
        $code = $LASTEXITCODE
    } finally {
        Pop-Location
        $ErrorActionPreference = $prevEap
    }
    if ($code -ne 0) { throw "pandoc PDF build failed (exit $code)." }

    Require-File $PdfPath 'BastionKryptonSuite-Manual.pdf'
    $sizeKB = [math]::Round((Get-Item $PdfPath).Length / 1KB)
    Write-Host "PDF produced: $PdfPath ($sizeKB KB)" -ForegroundColor Green
}

# ================================================================================ DRIVE
$failures = @()
try {
    if ($Coverage) { Invoke-Coverage }
    if ($Site)     { Invoke-Site }
    if ($Chm)      { Invoke-Chm }
    if ($Pdf)      { Invoke-Pdf }
} catch {
    Write-Host "`nERROR: $($_.Exception.Message)" -ForegroundColor Red
    exit 1
}

Write-Step "Done"
if ($Coverage) { Write-Host "  Coverage : $CoveragePath" }
if ($Site)     { Write-Host "  Site     : $SiteDir (GitHub Pages ready)" }
if ($Chm)      { Write-Host "  CHM      : $ChmPath" }
if ($Pdf)      { Write-Host "  PDF      : $PdfPath" }
exit 0
