'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
' VB.NET twin of Source\Krypton Explorer\Properties\Settings.Designer.cs (Bastion Phase 4c).

Option Strict On
Option Explicit On

Namespace Properties

    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.12.0.0")>
    Friend NotInheritable Partial Class Settings
        Inherits Global.System.Configuration.ApplicationSettingsBase

        Private Shared defaultInstance As Settings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New Settings()), Settings)

        Public Shared ReadOnly Property [Default]() As Settings
            Get
                Return defaultInstance
            End Get
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("")>
        Public Property HelpFileLocation() As String
            Get
                Return CStr(Me("HelpFileLocation"))
            End Get
            Set(value As String)
                Me("HelpFileLocation") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("30")>
        Public Property ThemeSelectedIndex() As Integer
            Get
                Return CInt(Me("ThemeSelectedIndex"))
            End Get
            Set(value As Integer)
                Me("ThemeSelectedIndex") = value
            End Set
        End Property

    End Class

End Namespace
