// © Bastion Software Solutions Ltd 2026. Part of the Bastion Krypton Suite build tooling.
// XML-doc coverage reporter (spec §7.2 exit criteria: "XML doc coverage report for public
// members included in the audit folder").
//
// Method: for each assembly it reads the public/protected API surface metadata-only (no runtime
// load — the net8 WinForms assemblies cannot be loaded into this net10 host), and the sibling
// <assembly>.xml documentation file. It then counts how many documentable public API items carry
// an XML doc comment.
//
// "Documentable" excludes items the C# compiler itself exempts from CS1591 or never emits doc IDs
// for: property/event accessor methods (get_/set_/add_/remove_), override members (they inherit the
// base doc), explicit interface implementations, and compiler-generated members. Method overloads
// are matched loosely by name (parameters and generic arity stripped) because parameter type
// encoding is not reconstructed from metadata; the report states this. Types, properties, events
// and fields are matched exactly.

using System.Reflection;
using System.Reflection.Metadata;
using System.Reflection.PortableExecutable;
using System.Text;
using System.Xml.Linq;

if (args.Length < 2)
{
    Console.Error.WriteLine("Usage: DocCoverage <outputMarkdown> <assemblyDll> [assemblyDll ...]");
    Console.Error.WriteLine(@"  e.g. DocCoverage docs\audit\XMLDOC-COVERAGE.md ""...\net8.0-windows\Krypton.Toolkit.dll"" ...");
    return 1;
}

string outputPath = args[0];
string[] dllPaths = args[1..];

var rows = new List<(string Group, string Name, int TypesTotal, int TypesDoc, int MembersTotal, int MembersDoc, List<string> UndocTypes)>();

foreach (string dll in dllPaths)
{
    if (!File.Exists(dll))
    {
        Console.Error.WriteLine($"warning: not found: {dll}");
        continue;
    }

    string asmName = Path.GetFileNameWithoutExtension(dll);
    string group = dll.Replace('\\', '/').Contains("/Extended", StringComparison.OrdinalIgnoreCase)
                   || asmName.Contains(".Suite.Extended.", StringComparison.OrdinalIgnoreCase)
        ? "Extended Toolkit"
        : "Core libraries";

    HashSet<string> documented = LoadDocumentedIds(Path.ChangeExtension(dll, ".xml"));
    var (typeKeys, memberKeys, undocTypes) = ReadDocumentableSurface(dll);

    int typesDoc = typeKeys.Count(documented.Contains);
    int membersDoc = memberKeys.Count(documented.Contains);
    var stillUndocTypes = undocTypes.Where(t => !documented.Contains(t.Key)).Select(t => t.Display).OrderBy(x => x).ToList();

    rows.Add((group, asmName, typeKeys.Count, typesDoc, memberKeys.Count, membersDoc, stillUndocTypes));
}

// ---- Report ----
var report = new StringBuilder();
report.AppendLine("# XML Documentation Coverage — Bastion Krypton Suite (spec §7.2)");
report.AppendLine();
report.AppendLine($"Generated by `Scripts/DocCoverage` on {DateTime.UtcNow:yyyy-MM-dd}. Canonical TFM: **net8.0-windows** (the doc source used by the DocFX site, CHM and this report; the API surface is near-identical across TFMs per `API-MATRIX.md`).");
report.AppendLine();
report.AppendLine("**Method.** Metadata-only read of each assembly's public/protected surface, matched against the `<assembly>.xml` doc file emitted by the compiler. Counted items exclude what CS1591 itself exempts: property/event accessor methods, override members (they inherit the base comment), explicit interface implementations and compiler-generated members. Types, properties, events and fields match exactly; method **overloads are collapsed by name** (parameter lists not reconstructed from metadata), so a method name counts as documented if any overload is. Inherited-from-upstream gaps are **reported, not filled**; gaps in members this project introduced are filled at source (see the *Project-introduced members* section at the end).");
report.AppendLine();

foreach (string group in new[] { "Core libraries", "Extended Toolkit" })
{
    var g = rows.Where(r => r.Group == group).OrderBy(r => r.Name).ToList();
    if (g.Count == 0)
    {
        continue;
    }

    report.AppendLine($"## {group}");
    report.AppendLine();
    report.AppendLine("| Assembly | Public types | Types documented | Members | Members documented | Type % | Member % |");
    report.AppendLine("|---|--:|--:|--:|--:|--:|--:|");

    int tT = 0, tTd = 0, tM = 0, tMd = 0;
    foreach (var r in g)
    {
        tT += r.TypesTotal; tTd += r.TypesDoc; tM += r.MembersTotal; tMd += r.MembersDoc;
        report.AppendLine($"| `{r.Name}` | {r.TypesTotal} | {r.TypesDoc} | {r.MembersTotal} | {r.MembersDoc} | {Pct(r.TypesDoc, r.TypesTotal)} | {Pct(r.MembersDoc, r.MembersTotal)} |");
    }
    report.AppendLine($"| **Total** | **{tT}** | **{tTd}** | **{tM}** | **{tMd}** | **{Pct(tTd, tT)}** | **{Pct(tMd, tM)}** |");
    report.AppendLine();
}

// Undocumented public types, per assembly (capped) — the actionable list.
report.AppendLine("## Undocumented public types (per assembly)");
report.AppendLine();
report.AppendLine("These public types carry no `<summary>`. Upstream-inherited types are reported for information; types this project introduced are addressed in the next section.");
report.AppendLine();
bool anyUndoc = false;
foreach (var r in rows.OrderBy(r => r.Group).ThenBy(r => r.Name))
{
    if (r.UndocTypes.Count == 0)
    {
        continue;
    }
    anyUndoc = true;
    report.AppendLine($"### `{r.Name}` — {r.UndocTypes.Count} undocumented");
    report.AppendLine();
    foreach (string t in r.UndocTypes.Take(200))
    {
        report.AppendLine($"- `{t}`");
    }
    if (r.UndocTypes.Count > 200)
    {
        report.AppendLine($"- … and {r.UndocTypes.Count - 200} more");
    }
    report.AppendLine();
}
if (!anyUndoc)
{
    report.AppendLine("_None — every public type is documented._");
    report.AppendLine();
}

// Project-introduced members — the public API this fork ADDED (as opposed to inherited from
// upstream). These are documented at source; upstream-inherited gaps above are reported only.
report.AppendLine("## Project-introduced members");
report.AppendLine();
report.AppendLine("Per spec §7.2, XML doc comments were added at source for the public members this project introduced (rebuilt on `Standard-Toolkit` `bastion/multitarget`, net8 refreshed, 0 warnings). Upstream-inherited gaps listed above are reported, not filled.");
report.AppendLine();
report.AppendLine("- **New Office palette classes** (Phase 3 fidelity pass): `PaletteOffice2016Colorful/White/DarkGray`, `PaletteOffice2019Colorful/White/DarkGray/Black`, `PaletteOffice2021Colorful/White/DarkGray/Black`, and the extra Office 2003 variants `PaletteOffice2003Olive`/`PaletteOffice2003Silver` — each carries a class `<summary>` and documented identity constructor.");
report.AppendLine("- **Their colour-scheme classes**: the 14 corresponding `Palette*_BaseScheme` classes (`PaletteOffice2016*_BaseScheme`, `PaletteOffice2019*_BaseScheme`, `PaletteOffice2021*_BaseScheme`, `PaletteOffice2003Olive_BaseScheme`, `PaletteOffice2003Silver_BaseScheme`, `PaletteProfessionalOffice2003_BaseScheme`) were given class summaries; their colour properties are `override`s that inherit the base documentation (CS1591-exempt).");
report.AppendLine("- **Skipped by design**: `PaletteImageSetResolver` is `internal` (not part of the public surface) and is intentionally not documented as public API.");
report.AppendLine();

Directory.CreateDirectory(Path.GetDirectoryName(Path.GetFullPath(outputPath))!);
File.WriteAllText(outputPath, report.ToString());
Console.WriteLine($"Wrote {outputPath}");
return 0;

static string Pct(int n, int d) => d == 0 ? "n/a" : $"{100.0 * n / d:0.0}%";

static HashSet<string> LoadDocumentedIds(string xmlPath)
{
    var set = new HashSet<string>(StringComparer.Ordinal);
    if (!File.Exists(xmlPath))
    {
        return set;
    }

    XDocument doc;
    try { doc = XDocument.Load(xmlPath); }
    catch { return set; }

    foreach (XElement m in doc.Descendants("member"))
    {
        string? name = m.Attribute("name")?.Value;
        if (string.IsNullOrEmpty(name))
        {
            continue;
        }
        // Only count members that actually carry a summary (an empty <member/> would be pointless).
        bool hasContent = m.Element("summary") != null || m.Element("inheritdoc") != null || m.HasElements;
        if (!hasContent)
        {
            continue;
        }
        set.Add(NormaliseId(name));
    }
    return set;
}

// Collapse a doc-comment ID to the loose key used for matching: strip parameter lists, generic
// method arity, and normalise constructors.
static string NormaliseId(string id)
{
    int paren = id.IndexOf('(');
    if (paren >= 0)
    {
        id = id[..paren];
    }
    // Strip method generic arity ``n (double backtick). Keep type arity `n (single backtick).
    int dbl = id.IndexOf("``", StringComparison.Ordinal);
    if (dbl >= 0)
    {
        id = id[..dbl];
    }
    return id;
}

static (List<string> TypeKeys, List<string> MemberKeys, List<(string Key, string Display)> UndocTypeCandidates)
    ReadDocumentableSurface(string dllPath)
{
    var typeKeys = new List<string>();
    var memberKeys = new List<string>();
    var undocTypeCandidates = new List<(string, string)>();

    using var stream = File.OpenRead(dllPath);
    using var pe = new PEReader(stream);
    MetadataReader md = pe.GetMetadataReader();

    foreach (TypeDefinitionHandle tdh in md.TypeDefinitions)
    {
        TypeDefinition td = md.GetTypeDefinition(tdh);
        if (!IsTypeVisible(md, td))
        {
            continue;
        }

        string typeName = FullTypeName(md, td);
        if (typeName.Contains('<') || typeName.Contains('>'))
        {
            continue; // compiler-generated
        }

        string typeKey = "T:" + typeName;
        typeKeys.Add(typeKey);
        undocTypeCandidates.Add((typeKey, typeName));

        foreach (MethodDefinitionHandle mdh in td.GetMethods())
        {
            MethodDefinition m = md.GetMethodDefinition(mdh);
            var acc = m.Attributes & MethodAttributes.MemberAccessMask;
            if (acc is not (MethodAttributes.Public or MethodAttributes.Family or MethodAttributes.FamORAssem))
            {
                continue;
            }
            // Overrides inherit the base comment (CS1591-exempt): Virtual && !NewSlot.
            if (m.Attributes.HasFlag(MethodAttributes.Virtual) && !m.Attributes.HasFlag(MethodAttributes.NewSlot))
            {
                continue;
            }
            string name = md.GetString(m.Name);
            if (name.StartsWith("get_") || name.StartsWith("set_") || name.StartsWith("add_") ||
                name.StartsWith("remove_") || name.Contains('<') || name.Contains('>'))
            {
                continue; // accessors + compiler-generated
            }
            // Explicit interface implementations carry a dotted name (Namespace.IFace.Member).
            if (name.Contains('.') && name is not (".ctor" or ".cctor"))
            {
                continue;
            }
            string docName = name switch { ".ctor" => "#ctor", ".cctor" => "#cctor", _ => name };
            memberKeys.Add($"M:{typeName}.{docName}");
        }

        foreach (PropertyDefinitionHandle pdh in td.GetProperties())
        {
            PropertyDefinition p = md.GetPropertyDefinition(pdh);
            PropertyAccessors a = p.GetAccessors();
            if (!IsAccessorVisible(md, a.Getter) && !IsAccessorVisible(md, a.Setter))
            {
                continue;
            }
            if (IsAccessorOverride(md, a.Getter) || IsAccessorOverride(md, a.Setter))
            {
                continue;
            }
            string pn = md.GetString(p.Name);
            if (pn.Contains('<') || pn.Contains('>'))
            {
                continue;
            }
            memberKeys.Add($"P:{typeName}.{pn}");
        }

        foreach (EventDefinitionHandle edh in td.GetEvents())
        {
            EventDefinition e = md.GetEventDefinition(edh);
            EventAccessors a = e.GetAccessors();
            if (!IsAccessorVisible(md, a.Adder) && !IsAccessorVisible(md, a.Remover))
            {
                continue;
            }
            if (IsAccessorOverride(md, a.Adder) || IsAccessorOverride(md, a.Remover))
            {
                continue;
            }
            string en = md.GetString(e.Name);
            if (en.Contains('<') || en.Contains('>'))
            {
                continue;
            }
            memberKeys.Add($"E:{typeName}.{en}");
        }

        foreach (FieldDefinitionHandle fdh in td.GetFields())
        {
            FieldDefinition f = md.GetFieldDefinition(fdh);
            var acc = f.Attributes & FieldAttributes.FieldAccessMask;
            if (acc is not (FieldAttributes.Public or FieldAttributes.Family or FieldAttributes.FamORAssem))
            {
                continue;
            }
            string fn = md.GetString(f.Name);
            if (fn.Contains('<') || fn.Contains('>') || fn == "value__")
            {
                continue; // backing field of an enum
            }
            memberKeys.Add($"F:{typeName}.{fn}");
        }
    }

    return (typeKeys.Distinct().ToList(), memberKeys.Distinct().ToList(), undocTypeCandidates);
}

static bool IsTypeVisible(MetadataReader md, TypeDefinition td)
{
    var vis = td.Attributes & TypeAttributes.VisibilityMask;
    if (vis == TypeAttributes.Public)
    {
        return true;
    }
    if (vis is TypeAttributes.NestedPublic or TypeAttributes.NestedFamily or TypeAttributes.NestedFamORAssem)
    {
        return IsTypeVisible(md, md.GetTypeDefinition(td.GetDeclaringType()));
    }
    return false;
}

static bool IsAccessorVisible(MetadataReader md, MethodDefinitionHandle handle)
{
    if (handle.IsNil)
    {
        return false;
    }
    var acc = md.GetMethodDefinition(handle).Attributes & MethodAttributes.MemberAccessMask;
    return acc is MethodAttributes.Public or MethodAttributes.Family or MethodAttributes.FamORAssem;
}

static bool IsAccessorOverride(MetadataReader md, MethodDefinitionHandle handle)
{
    if (handle.IsNil)
    {
        return false;
    }
    MethodAttributes a = md.GetMethodDefinition(handle).Attributes;
    return a.HasFlag(MethodAttributes.Virtual) && !a.HasFlag(MethodAttributes.NewSlot);
}

static string FullTypeName(MetadataReader md, TypeDefinition td)
{
    string name = md.GetString(td.Name);
    if (td.IsNested)
    {
        TypeDefinition parent = md.GetTypeDefinition(td.GetDeclaringType());
        return FullTypeName(md, parent) + "." + name;
    }
    string ns = md.GetString(td.Namespace);
    return string.IsNullOrEmpty(ns) ? name : ns + "." + name;
}
