'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
' VB.NET twin of Source\Krypton Workspace Examples\Memo Editor\Properties\Resources.Designer.cs (Bastion Phase 4c).

Option Strict On
Option Explicit On

Namespace My.Resources

    ''' <summary>
    '''   A strongly-typed resource class, for looking up localized strings, etc.
    ''' </summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>
    Friend Module Resources

        Private resourceMan As Global.System.Resources.ResourceManager

        Private resourceCulture As Global.System.Globalization.CultureInfo

        ''' <summary>
        '''   Returns the cached ResourceManager instance used by this class.
        ''' </summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("MemoEditor.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property

        ''' <summary>
        '''   Overrides the current thread's CurrentUICulture property for all
        '''   resource lookups using this strongly typed resource class.
        ''' </summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set(value As Global.System.Globalization.CultureInfo)
                resourceCulture = value
            End Set
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property close16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("close16", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property close24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("close24", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property close32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("close32", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property closeAll16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("closeAll16", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property closeAll24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("closeAll24", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property closeAll32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("closeAll32", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property horz16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("horz16", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property horz32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("horz32", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property note16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("note16", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property note24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("note24", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property note32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("note32", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property Tabs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tabs", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property vert16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("vert16", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property vert32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("vert32", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
