' VB.NET twin of Source\Krypton Toolkit Examples\KryptonLinkWrapLabel Example\Program.cs (Bastion Phase 4c).

Imports System
Imports System.Windows.Forms

Friend Module Program

    ''' <summary>
    '''  The main entry point for the application.
    ''' </summary>
    <STAThread>
    Sub Main()
        ' To customize application configuration such as set high DPI settings or default font,
        ' see https://aka.ms/applicationconfiguration.
#If NET6_0_OR_GREATER Then
        ' Bastion: the C# twin calls the source-generated ApplicationConfiguration.Initialize();
        ' VB has no such generator, so apply the equivalent bootstrap explicitly.
        Application.SetHighDpiMode(HighDpiMode.SystemAware)
        Application.EnableVisualStyles()
        Application.SetCompatibleTextRenderingDefault(False)
#Else
        ' Bastion: ApplicationConfiguration is generated by the WinForms SDK on net6.0+ only;
        ' fall back to the classic bootstrap on .NET Framework and net5.0.
        Application.EnableVisualStyles()
        Application.SetCompatibleTextRenderingDefault(False)
#End If
        Application.Run(New Form1())
    End Sub

End Module
