using System;
using System.Windows.Forms;

namespace KryptonLinkWrapLabelExample
{
    internal static class Program
    {
        /// <summary>
        ///  The main entry point for the application.
        /// </summary>
        [STAThread]
        static void Main()
        {
            // To customize application configuration such as set high DPI settings or default font,
            // see https://aka.ms/applicationconfiguration.
#if NET6_0_OR_GREATER
            ApplicationConfiguration.Initialize();
#else
            // Bastion: ApplicationConfiguration is generated by the WinForms SDK on net6.0+ only;
            // fall back to the classic bootstrap on .NET Framework and net5.0.
            Application.EnableVisualStyles();
            Application.SetCompatibleTextRenderingDefault(false);
#endif
            Application.Run(new Form1());
        }
    }
}
