'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
' VB.NET twin of Source\Krypton Ribbon Examples\Outlook Mail Clone\Properties\Resources.Designer.cs (Bastion Phase 4c).

Option Strict On
Option Explicit On

Namespace My.Resources

    ''' <summary>
    '''   A strongly-typed resource class, for looking up localized strings, etc.
    ''' </summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>
    Friend Module Resources

        Private resourceMan As Global.System.Resources.ResourceManager

        Private resourceCulture As Global.System.Globalization.CultureInfo

        ''' <summary>
        '''   Returns the cached ResourceManager instance used by this class.
        ''' </summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("OutlookMailClone.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property

        ''' <summary>
        '''   Overrides the current thread's CurrentUICulture property for all
        '''   resource lookups using this strongly typed resource class.
        ''' </summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set(value As Global.System.Globalization.CultureInfo)
                resourceCulture = value
            End Set
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property AllBorder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AllBorder", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property ApplyStyles() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ApplyStyles", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property AppMenuClose() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AppMenuClose", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property AppMenuDelete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AppMenuDelete", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property AppMenuMemoStyle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AppMenuMemoStyle", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property AppMenuMove() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AppMenuMove", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property AppMenuNewMailMessage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AppMenuNewMailMessage", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property AppMenuPrint() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AppMenuPrint", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property AppMenuPrintPreview() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AppMenuPrintPreview", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property AppMenuPrintStyles() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AppMenuPrintStyles", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property AppMenuProperties() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AppMenuProperties", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property AppMenuQuickPrint() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AppMenuQuickPrint", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property AppMenuSave() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AppMenuSave", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property AppMenuSaveAs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AppMenuSaveAs", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property AppMenuSendMessage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AppMenuSendMessage", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property BookmarkLarge() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BookmarkLarge", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property BookmarkSmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BookmarkSmall", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property BordersAndShading() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BordersAndShading", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property BottomBorder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BottomBorder", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property BottomBorder1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BottomBorder1", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property BrowseThemesSmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BrowseThemesSmall", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property ChangeStyles() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ChangeStyles", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property ChartLarge() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ChartLarge", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property ChartSmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ChartSmall", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property ClipArtLarge() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ClipArtLarge", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property ClipboardCopy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ClipboardCopy", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property ClipboardCut() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ClipboardCut", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property ClipboardFormatPainter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ClipboardFormatPainter", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property ClipboardPaste() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ClipboardPaste", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property ClipboardPasteSmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ClipboardPasteSmall", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property ClipboardPasteSpecial() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ClipboardPasteSpecial", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property CodeMacros() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CodeMacros", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property CodeVisualBasic() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CodeVisualBasic", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property ColorsSmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ColorsSmall", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property DateTimeSmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DateTimeSmall", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property DelayDeliveryLarge() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DelayDeliveryLarge", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property DelayDeliverySmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DelayDeliverySmall", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property DiagonalDownBorder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DiagonalDownBorder", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property DiagonalUpBorder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DiagonalUpBorder", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property DirectRepliesToLarge() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DirectRepliesToLarge", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property DrawingCanvasSmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DrawingCanvasSmall", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property DropCapSmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DropCapSmall", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property EffectsSmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EffectsSmall", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property EquationLarge() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EquationLarge", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property EquationSmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EquationSmall", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property ExcelSpreadsheetSmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ExcelSpreadsheetSmall", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property FieldsSmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FieldsSmall", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property FindReplaceSmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FindReplaceSmall", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property FindSmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FindSmall", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property FollowUp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FollowUp", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property FollowUp1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FollowUp1", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property FontsSmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FontsSmall", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property FormDesignAForm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FormDesignAForm", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property FormDesignThisForm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FormDesignThisForm", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property FormPublish() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FormPublish", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property FormPublishSmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FormPublishSmall", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property HelpSmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HelpSmall", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property HorizontalLineLarge() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HorizontalLineLarge", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property HorizontalLineSmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HorizontalLineSmall", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property HorizontalLineSmall1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HorizontalLineSmall1", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property HTMLSmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HTMLSmall", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property HyperlinkLarge() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HyperlinkLarge", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property HyperlinkSmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HyperlinkSmall", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property IncludeAttachFile() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IncludeAttachFile", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property IncludeAttachFileSmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IncludeAttachFileSmall", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property IncludeAttachItem() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IncludeAttachItem", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property IncludeAttachItemSmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IncludeAttachItemSmall", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property IncludeBusinessCard() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IncludeBusinessCard", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property IncludeBusinessCardSmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IncludeBusinessCardSmall", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property IncludeCalendar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IncludeCalendar", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property IncludeCalendarSmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IncludeCalendarSmall", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property IncludeSignature() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IncludeSignature", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property IncludeSignatureSmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IncludeSignatureSmall", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property InsideBorder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("InsideBorder", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property InsideHorzBorder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("InsideHorzBorder", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property InsideVertBorder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("InsideVertBorder", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property LeftBorder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LeftBorder", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property LineSpacing() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LineSpacing", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property Main_Icon_64_x_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Main Icon 64 x 64", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property MoreOptionsSmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MoreOptionsSmall", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property MultiLevelList() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MultiLevelList", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property NamesAddressBook() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NamesAddressBook", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property NamesCheckNames() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NamesCheckNames", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property NamesGroup() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NamesGroup", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property NoBorder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NoBorder", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property ObjectSmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ObjectSmall", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property OptionsFollowUp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OptionsFollowUp", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property OptionsFollowUpSmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OptionsFollowUpSmall", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property OptionsHighImportance() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OptionsHighImportance", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property OptionsLowImportance() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OptionsLowImportance", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property OptionsReminder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OptionsReminder", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property OptionsToday() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OptionsToday", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property OptionsTomorrow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OptionsTomorrow", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property OptionsWeek() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OptionsWeek", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property OtherFolderSmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OtherFolderSmall", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property OutsideBorder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OutsideBorder", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property PageColorLarge() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PageColorLarge", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property PicturesLarge() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PicturesLarge", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property PlainTextSmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PlainTextSmall", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property ProofingResearchSmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ProofingResearchSmall", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property ProofingSetLanguageSmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ProofingSetLanguageSmall", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property ProofingSpelling() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ProofingSpelling", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property ProofingSpellingSmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ProofingSpellingSmall", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property ProofingThesaurusSmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ProofingThesaurusSmall", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property ProofingTranslateSmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ProofingTranslateSmall", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property ProofingTransScreentipSmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ProofingTransScreentipSmall", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property ProofingWordCountSmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ProofingWordCountSmall", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property QATDeleteSmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("QATDeleteSmall", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property QATForwardSmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("QATForwardSmall", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property QATQuickPrintSmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("QATQuickPrintSmall", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property QATRedoSmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("QATRedoSmall", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property QATSaveSmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("QATSaveSmall", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property QATUndoSmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("QATUndoSmall", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property QuickPartsLarge() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("QuickPartsLarge", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property QuickPartsSmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("QuickPartsSmall", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property QuickStyles() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("QuickStyles", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property RichTextSmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RichTextSmall", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property RightBorder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RightBorder", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property SaveSentItemLarge() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SaveSentItemLarge", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property SaveThemesSmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SaveThemesSmall", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property SelectSmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SelectSmall", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property SendMail() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SendMail", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property SendRepliesToSmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SendRepliesToSmall", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property Shading() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Shading", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property ShapesLarge() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ShapesLarge", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property ShapesSmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ShapesSmall", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property ShowBccLarge() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ShowBccLarge", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property ShowFromLarge() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ShowFromLarge", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property SmartArtLarge() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SmartArtLarge", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property SmartArtSmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SmartArtSmall", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property SortAscending() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SortAscending", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property SpacingDouble() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SpacingDouble", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property SpacingOne() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SpacingOne", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property SpacingOneHalf() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SpacingOneHalf", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property SpacingParagraph() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SpacingParagraph", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property StyleSet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StyleSet", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property SymbolLarge() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SymbolLarge", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property SymbolSmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SymbolSmall", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property TableDrawSmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TableDrawSmall", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property TablesLarge() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TablesLarge", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property TableSmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TableSmall", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property TextAlignCenter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TextAlignCenter", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property TextAlignLeft() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TextAlignLeft", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property TextAlignRight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TextAlignRight", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property TextBackColor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TextBackColor", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property TextBold() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TextBold", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property TextBoxLarge() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TextBoxLarge", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property TextBoxSmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TextBoxSmall", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property TextBulletNumbers() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TextBulletNumbers", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property TextBulletPoints() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TextBulletPoints", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property TextChangeCase() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TextChangeCase", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property TextColor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TextColor", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property TextFontLarger() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TextFontLarger", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property TextFontSmaller() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TextFontSmaller", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property TextItalics() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TextItalics", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property TextJustify() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TextJustify", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property TextRubout() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TextRubout", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property TextShowHideMarkup() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TextShowHideMarkup", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property TextStrikeout() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TextStrikeout", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property TextSubscript() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TextSubscript", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property TextSuperscript() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TextSuperscript", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property TextTabLeft() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TextTabLeft", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property TextTabRight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TextTabRight", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property TextUnderline() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TextUnderline", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property ThemesLarge() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ThemesLarge", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property ThemesSmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ThemesSmall", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property TopBorder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TopBorder", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property TrackingSmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TrackingSmall", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property UseVotingButtonsLarge() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("UseVotingButtonsLarge", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property ViewGridlines() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ViewGridlines", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property WordArtLarge() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WordArtLarge", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property WordArtSmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WordArtSmall", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend ReadOnly Property ZoomLarge() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ZoomLarge", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
