// © Bastion Software Solutions Ltd 2026. Part of the Bastion Krypton Suite build tooling.
// Dumps the public API surface (types + members) of each Krypton assembly for every TFM
// using metadata-only reading (no runtime load), then diffs the surfaces across TFMs.
// Output: docs/audit/API-MATRIX.md — differences must exactly match documented #if degradations.

using System.Reflection;
using System.Reflection.Metadata;
using System.Reflection.PortableExecutable;
using System.Text;

if (args.Length < 2)
{
    Console.Error.WriteLine("Usage: ApiMatrix <binRoot> <outputMarkdown> [assemblyName ...]");
    Console.Error.WriteLine(@"  e.g. ApiMatrix D:\Krypton-Ultimate\Standard-Toolkit\Bin\Release D:\Krypton-Ultimate\docs\audit\API-MATRIX.md");
    return 1;
}

string binRoot = args[0];
string outputPath = args[1];
string[] assemblies = args.Length > 2
    ? args[2..]
    : ["Krypton.Toolkit", "Krypton.Ribbon", "Krypton.Navigator", "Krypton.Workspace", "Krypton.Docking"];

var tfms = Directory.GetDirectories(binRoot)
    .Select(Path.GetFileName)
    .Where(d => d is not null && d.StartsWith("net"))
    .OrderBy(TfmRank)
    .Select(d => d!)
    .ToList();

var report = new StringBuilder();
report.AppendLine("# API Matrix — public surface comparison across TFMs");
report.AppendLine();
report.AppendLine($"Generated by `Scripts/ApiMatrix` from `{binRoot}`.");
report.AppendLine($"TFMs compared: {string.Join(", ", tfms)}.");
report.AppendLine();
report.AppendLine("Method: metadata-only read of each assembly; the surface is every public/protected type and member,");
report.AppendLine("rendered as a stable signature string. A member listed under \"differences\" is absent from at least one TFM.");
report.AppendLine();

bool anyDifference = false;

foreach (string asmName in assemblies)
{
    report.AppendLine($"## {asmName}");
    report.AppendLine();

    var surfaces = new Dictionary<string, HashSet<string>>();
    foreach (string tfm in tfms)
    {
        string dll = Path.Combine(binRoot, tfm, asmName + ".dll");
        if (!File.Exists(dll))
        {
            report.AppendLine($"- ⚠️ `{tfm}`: assembly not found — build incomplete?");
            continue;
        }
        surfaces[tfm] = ReadPublicSurface(dll);
    }

    if (surfaces.Count == 0)
    {
        report.AppendLine("- no assemblies found.");
        report.AppendLine();
        continue;
    }

    var all = surfaces.Values.Aggregate(new HashSet<string>(), (acc, s) => { acc.UnionWith(s); return acc; });
    var common = surfaces.Values.Aggregate(new HashSet<string>(all), (acc, s) => { acc.IntersectWith(s); return acc; });
    var diffs = all.Except(common).OrderBy(s => s, StringComparer.Ordinal).ToList();

    report.AppendLine($"- Union surface: **{all.Count}** signatures; common to all TFMs: **{common.Count}**; differing: **{diffs.Count}**.");
    report.AppendLine();

    if (diffs.Count > 0)
    {
        anyDifference = true;
        report.AppendLine("| Signature | Present in | Absent from |");
        report.AppendLine("|---|---|---|");
        foreach (string sig in diffs)
        {
            var present = tfms.Where(t => surfaces.TryGetValue(t, out var s) && s.Contains(sig)).ToList();
            var absent = tfms.Where(t => surfaces.ContainsKey(t) && !surfaces[t].Contains(sig)).ToList();
            report.AppendLine($"| `{sig.Replace("|", "\\|")}` | {Compact(present)} | {Compact(absent)} |");
        }
        report.AppendLine();
    }
}

report.AppendLine("---");
report.AppendLine(anyDifference
    ? "Result: differences found — each row above must correspond to a documented `#if` degradation (see CHANGES.md per-TFM feature matrix)."
    : "Result: ✅ the public API surface is identical across every TFM.");

Directory.CreateDirectory(Path.GetDirectoryName(Path.GetFullPath(outputPath))!);
File.WriteAllText(outputPath, report.ToString());
Console.WriteLine($"Wrote {outputPath}");
return anyDifference ? 2 : 0;

static string Compact(List<string> tfms) => tfms.Count == 0 ? "—" : string.Join(", ", tfms);

static int TfmRank(string? tfm) => tfm switch
{
    "net46" => 0, "net47" => 1, "net472" => 2, "net48" => 3, "net481" => 4,
    "net5.0-windows" => 5, "net6.0-windows" => 6, "net7.0-windows" => 7,
    "net8.0-windows" => 8, "net9.0-windows" => 9, "net10.0-windows" => 10,
    _ => 99
};

static HashSet<string> ReadPublicSurface(string dllPath)
{
    var result = new HashSet<string>();
    using var stream = File.OpenRead(dllPath);
    using var pe = new PEReader(stream);
    MetadataReader md = pe.GetMetadataReader();

    foreach (TypeDefinitionHandle tdh in md.TypeDefinitions)
    {
        TypeDefinition td = md.GetTypeDefinition(tdh);
        if (!IsTypeVisible(md, td))
        {
            continue;
        }

        string typeName = FullTypeName(md, td);
        result.Add($"T:{typeName}");

        foreach (MethodDefinitionHandle mdh in td.GetMethods())
        {
            MethodDefinition m = md.GetMethodDefinition(mdh);
            var acc = m.Attributes & MethodAttributes.MemberAccessMask;
            if (acc is not (MethodAttributes.Public or MethodAttributes.Family or MethodAttributes.FamORAssem))
            {
                continue;
            }
            string name = md.GetString(m.Name);
            // Parameter arity keeps the signature stable without full type decoding.
            BlobReader sigReader = md.GetBlobReader(m.Signature);
            SignatureHeader header = sigReader.ReadSignatureHeader();
            if (header.IsGeneric)
            {
                sigReader.ReadCompressedInteger();
            }
            int paramCount = sigReader.ReadCompressedInteger();
            result.Add($"M:{typeName}.{name}/{paramCount}");
        }

        foreach (PropertyDefinitionHandle pdh in td.GetProperties())
        {
            PropertyDefinition p = md.GetPropertyDefinition(pdh);
            PropertyAccessors accessors = p.GetAccessors();
            bool visible = IsAccessorVisible(md, accessors.Getter) || IsAccessorVisible(md, accessors.Setter);
            if (visible)
            {
                result.Add($"P:{typeName}.{md.GetString(p.Name)}");
            }
        }

        foreach (EventDefinitionHandle edh in td.GetEvents())
        {
            EventDefinition e = md.GetEventDefinition(edh);
            EventAccessors accessors = e.GetAccessors();
            bool visible = IsAccessorVisible(md, accessors.Adder) || IsAccessorVisible(md, accessors.Remover);
            if (visible)
            {
                result.Add($"E:{typeName}.{md.GetString(e.Name)}");
            }
        }

        foreach (FieldDefinitionHandle fdh in td.GetFields())
        {
            FieldDefinition f = md.GetFieldDefinition(fdh);
            var acc = f.Attributes & FieldAttributes.FieldAccessMask;
            if (acc is FieldAttributes.Public or FieldAttributes.Family or FieldAttributes.FamORAssem)
            {
                result.Add($"F:{typeName}.{md.GetString(f.Name)}");
            }
        }
    }

    return result;
}

static bool IsTypeVisible(MetadataReader md, TypeDefinition td)
{
    var vis = td.Attributes & TypeAttributes.VisibilityMask;
    if (vis == TypeAttributes.Public)
    {
        return true;
    }
    // Nested public/protected types are only part of the surface if every enclosing type is visible.
    if (vis is TypeAttributes.NestedPublic or TypeAttributes.NestedFamily or TypeAttributes.NestedFamORAssem)
    {
        return IsTypeVisible(md, md.GetTypeDefinition(td.GetDeclaringType()));
    }
    return false;
}

static bool IsAccessorVisible(MetadataReader md, MethodDefinitionHandle handle)
{
    if (handle.IsNil)
    {
        return false;
    }
    var acc = md.GetMethodDefinition(handle).Attributes & MethodAttributes.MemberAccessMask;
    return acc is MethodAttributes.Public or MethodAttributes.Family or MethodAttributes.FamORAssem;
}

static string FullTypeName(MetadataReader md, TypeDefinition td)
{
    string name = md.GetString(td.Name);
    if (td.IsNested)
    {
        TypeDefinition parent = md.GetTypeDefinition(td.GetDeclaringType());
        return FullTypeName(md, parent) + "+" + name;
    }
    string ns = md.GetString(td.Namespace);
    return string.IsNullOrEmpty(ns) ? name : ns + "." + name;
}
