'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
' VB.NET twin of Source\Krypton Ribbon Examples\Ribbon Controls\Properties\Settings.Designer.cs (Bastion Phase 4c).
' NOTE: the C# twin nests this class in the RibbonControls.Properties namespace;
' the VB twin follows the batch convention of omitting Namespace blocks, so the
' class lives in the project root namespace (RibbonControls).

Option Strict On
Option Explicit On

<Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),
 Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.11.0.0")>
Friend NotInheritable Partial Class Settings
    Inherits Global.System.Configuration.ApplicationSettingsBase

    Private Shared ReadOnly defaultInstance As Settings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New Settings()), Settings)

    Public Shared ReadOnly Property [Default]() As Settings
        Get
            Return defaultInstance
        End Get
    End Property

    <Global.System.Configuration.UserScopedSettingAttribute(),
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
     Global.System.Configuration.DefaultSettingValueAttribute("False")>
    Public Property RibbonCheckBox() As Boolean
        Get
            Return CBool(Me("RibbonCheckBox"))
        End Get
        Set(value As Boolean)
            Me("RibbonCheckBox") = value
        End Set
    End Property

    <Global.System.Configuration.UserScopedSettingAttribute(),
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
     Global.System.Configuration.DefaultSettingValueAttribute("False")>
    Public Property CheckBox() As Boolean
        Get
            Return CBool(Me("CheckBox"))
        End Get
        Set(value As Boolean)
            Me("CheckBox") = value
        End Set
    End Property

    <Global.System.Configuration.UserScopedSettingAttribute(),
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
     Global.System.Configuration.DefaultSettingValueAttribute("2018-01-01")>
    Public Property DateTimePicker1() As Global.System.DateTime
        Get
            Return CType(Me("DateTimePicker1"), Global.System.DateTime)
        End Get
        Set(value As Global.System.DateTime)
            Me("DateTimePicker1") = value
        End Set
    End Property

End Class
